apiVersion: apps/v1

kind: Deployment
metadata:
  name: my3-deployment
spec:
  selector:
    matchLabels:
      app: my-app4
  replicas: 9 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-app4
    spec:
      containers:
      - name: my-app3
        image:  devopstrainingschool/nodejs-jenkins:2023
        ports:
        - containerPort: 8080
